---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tokokit2/public_html/
    - /bin/cp -R ajax $DEPLOYPATH
    - /bin/cp -R asset $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R other $DEPLOYPATH
    - /bin/cp -R util $DEPLOYPATH
    - /bin/cp * $DEPLOYPATH
