INSERT INTO province (name) VALUES
('Nanggroe Aceh Darussalam'),
('Sumatera Utara'),
('Sumatera Barat'),
('Sumatera Selatan'),
('Riau'),
('Kepulauan Riau'),
('Jambi'),
('Bengkulu'),
('Bangka Belitung'),
('Lampung'),
('Banten'),
('Jawa Barat'),
('Jawa Tengah'),
('Jawa Timur'),
('DKI Jakarta'),
('Daerah Istimewa Yogyakarta'),
('Bali'),
('Nusa Tenggara Barat'),
('Nusa Tenggara Timur'),
('Kalimantan Barat'),
('Kalimantan Selatan'),
('Kalimantan Tengah'),
('Kalimantan Timur'),
('Kalimantan Utara'),
('Gorontalo'),
('Sulawesi Selatan'),
('Sulawesi Tenggara'),
('Sulawesi Tengah'),
('Sulawesi Utara'),
('Sulawesi Barat'),
('Maluku'),
('Maluku Utara'),
('Papua'),
('Papua Barat');