INSERT INTO city (name, id_prov) VALUES 
('Aceh Barat', 1),
('Aceh Barat Daya', 1),
('Aceh Besar', 1),
('Aceh Jaya', 1),
('Aceh Selatan', 1),
('Aceh Singkil', 1),
('Aceh Tamiang', 1),
('Aceh Tengah', 1),
('Aceh Tenggara', 1),
('Aceh Timur', 1),
('Aceh Utara', 1),
('Bener Meriah', 1),
('Bireuen', 1),
('Gayo Lues', 1),
('Nagan Raya', 1),
('Pidie', 1),
('Pidie Jaya', 1),
('Simeulue', 1),
('Banda Aceh', 1),
('Langsa', 1),
('Lhokseumawe', 1),
('Sabang', 1),
('Subulussalam', 1),
('Asahan', 2),
('Batubara', 2),
('Dairi', 2),
('Deli Serdang', 2),
('Humbang Hasundutan', 2),
('Karo', 2),
('Labuhanbatu', 2),
('Labuhanbatu Selatan', 2),
('Labuhanbatu Utara', 2),
('Langkat', 2),
('Mandailing Natal', 2),
('Nias', 2),
('Nias Barat', 2),
('Nias Selatan', 2),
('Nias Utara', 2),
('Padang Lawas', 2),
('Padang Lawas Utara', 2),
('Pakpak Bharat', 2),
('Samosir', 2),
('Serdang Bedagai', 2),
('Simalungun', 2),
('Tapanuli Selatan', 2),
('Tapanuli Tengah', 2),
('Tapanuli Utara', 2),
('Toba Samosir', 2),
('Binjai', 2),
('Gunungsitoli', 2),
('Medan', 2),
('Padangsidempuan', 2),
('Pematangsiantar', 2),
('Sibolga', 2),
('Tanjungbalai', 2),
('Tebing Tinggi', 2),
('Agam', 3),
('Dharmasraya', 3),
('Kepulauan Mentawai', 3),
('Lima Puluh Kota', 3),
('Padang Pariaman', 3),
('Pasaman', 3),
('Pasaman Barat', 3),
('Pesisir Selatan', 3),
('Sijunjung', 3),
('Solok', 3),
('Solok Selatan', 3),
('Tanah Datar', 3),
('Bukittinggi', 3),
('Padang', 3),
('Padangpanjang', 3),
('Pariaman', 3),
('Payakumbuh', 3),
('Sawahlunto', 3),
('Solok', 3),
('Banyuasin', 4),
('Empat Lawang', 4),
('Lahat', 4),
('Muara Enim', 4),
('Musi Banyuasin', 4),
('Musi Rawas', 4),
('Musi Rawas Utara', 4),
('Ogan Ilir', 4),
('Ogan Komering Ilir', 4),
('Ogan Komering Ulu', 4),
('Ogan Komering Ulu Selatan', 4),
('Ogan Komering Ulu Timur', 4),
('Penukal Abab Lematang Ilir', 4),
('Lubuklinggau', 4),
('Pagar Alam', 4),
('Palembang', 4),
('Prabumulih', 4),
('Bengkalis', 5),
('Indragiri Hilir', 5),
('Indragiri Hulu', 5),
('Kampar', 5),
('Kepulauan Meranti', 5),
('Kuantan Singingi', 5),
('Pelalawan', 5),
('Rokan Hilir', 5),
('Rokan Hulu', 5),
('Siak', 5),
('Dumai', 5),
('Pekanbaru', 5),
('Bintan', 6),
('Karimun', 6),
('Kepulauan Anambas', 6),
('Lingga', 6),
('Natuna', 6),
('Batam', 6),
('Tanjung Pinang', 6),
('Batanghari', 7),
('Bungo', 7),
('Kerinci', 7),
('Merangin', 7),
('Muaro Jambi', 7),
('Sarolangun', 7),
('Tanjung Jabung Barat', 7),
('Tanjung Jabung Timur', 7),
('Tebo', 7),
('Jambi', 7),
('Sungai Penuh', 7),
('Bengkulu Selatan', 8),
('Bengkulu Tengah', 8),
('Bengkulu Utara', 8),
('Kaur', 8),
('Kepahiang', 8),
('Lebong', 8),
('Mukomuko', 8),
('Rejang Lebong', 8),
('Seluma', 8),
('Bengkulu', 8),
('Bangka', 9),
('Bangka Barat', 9),
('Bangka Selatan', 9),
('Bangka Tengah', 9),
('Belitung', 9),
('Belitung Timur', 9),
('Pangkal Pinang', 9),
('Lampung Tengah', 10),
('Lampung Utara', 10),
('Lampung Selatan', 10),
('Lampung Barat', 10),
('Lampung Timur', 10),
('Mesuji', 10),
('Pesawaran', 10),
('Pesisir Barat', 10),
('Pringsewu', 10),
('Tulang Bawang', 10),
('Tulang Bawang Barat', 10),
('Tanggamus', 10),
('Way Kanan', 10),
('Bandar Lampung', 10),
('Metro', 10),
('Lebak', 11),
('Pandeglang', 11),
('Serang', 11),
('Tangerang', 11),
('Cilegon', 11),
('Serang', 11),
('Tangerang', 11),
('Tangerang Selatan', 11),
('Bandung', 12),
('Bandung Barat', 12),
('Bekasi', 12),
('Bogor', 12),
('Ciamis', 12),
('Cianjur', 12),
('Cirebon', 12),
('Garut', 12),
('Indramayu', 12),
('Karawang', 12),
('Kuningan', 12),
('Majalengka', 12),
('Pangandaran', 12),
('Purwakarta', 12),
('Subang', 12),
('Sukabumi', 12),
('Sumedang', 12),
('Tasikmalaya', 12),
('Bandung', 12),
('Banjar', 12),
('Bekasi', 12),
('Bogor', 12),
('Cimahi', 12),
('Cirebon', 12),
('Depok', 12),
('Sukabumi', 12),
('Tasikmalaya', 12),
('Banjarnegara', 13),
('Banyumas', 13),
('Batang', 13),
('Blora', 13),
('Boyolali', 13),
('Brebes', 13),
('Cilacap', 13),
('Demak', 13),
('Grobogan', 13),
('Jepara', 13),
('Karanganyar', 13),
('Kebumen', 13),
('Kendal', 13),
('Klaten', 13),
('Kudus', 13),
('Magelang', 13),
('Pati', 13),
('Pekalongan', 13),
('Pemalang', 13),
('Purbalingga', 13),
('Purworejo', 13),
('Rembang', 13),
('Semarang', 13),
('Sragen', 13),
('Sukoharjo', 13),
('Tegal', 13),
('Temanggung', 13),
('Wonogiri', 13),
('Wonosobo', 13),
('Magelang', 13),
('Pekalongan', 13),
('Salatiga', 13),
('Semarang', 13),
('Surakarta', 13),
('Tegal', 13),
('Bangkalan', 14),
('Banyuwangi', 14),
('Blitar', 14),
('Bojonegoro', 14),
('Bondowoso', 14),
('Gresik', 14),
('Jember', 14),
('Jombang', 14),
('Kediri', 14),
('Lamongan', 14),
('Lumajang', 14),
('Madiun', 14),
('Magetan', 14),
('Malang', 14),
('Mojokerto', 14),
('Nganjuk', 14),
('Ngawi', 14),
('Pacitan', 14),
('Pamekasan', 14),
('Pasuruan', 14),
('Ponorogo', 14),
('Probolinggo', 14),
('Sampang', 14),
('Sidoarjo', 14),
('Situbondo', 14),
('Sumenep', 14),
('Trenggalek', 14),
('Tuban', 14),
('Tulungagung', 14),
('Batu', 14),
('Blitar', 14),
('Kediri', 14),
('Madiun', 14),
('Malang', 14),
('Mojokerto', 14),
('Pasuruan', 14),
('Probolinggo', 14),
('Surabaya', 14),
('Administrasi Jakarta Barat', 15),
('Administrasi Jakarta Pusat', 15),
('Administrasi Jakarta Selatan', 15),
('Administrasi Jakarta Timur', 15),
('Administrasi Jakarta Utara', 15),
('Administrasi Kepulauan Seribu', 15),
('Bantul', 16),
('Gunungkidul', 16),
('Kulon Progo', 16),
('Sleman', 16),
('Yogyakarta', 16),
('Badung', 17),
('Bangli', 17),
('Buleleng', 17),
('Gianyar', 17),
('Jembrana', 17),
('Karangasem', 17),
('Klungkung', 17),
('Tabanan', 17),
('Denpasar', 17),
('Bima', 18),
('Dompu', 18),
('Lombok Barat', 18),
('Lombok Tengah', 18),
('Lombok Timur', 18),
('Lombok Utara', 18),
('Sumbawa', 18),
('Sumbawa Barat', 18),
('Bima', 18),
('Mataram', 18),
('Alor', 19),
('Belu', 19),
('Ende', 19),
('Flores Timur', 19),
('Kupang', 19),
('Lembata', 19),
('Malaka', 19),
('Manggarai', 19),
('Manggarai Barat', 19),
('Manggarai Timur', 19),
('Ngada', 19),
('Nagekeo', 19),
('Rote Ndao', 19),
('Sabu Raijua', 19),
('Sikka', 19),
('Sumba Barat', 19),
('Sumba Barat Daya', 19),
('Sumba Tengah', 19),
('Sumba Timur', 19),
('Timor Tengah Selatan', 19),
('Timor Tengah Utara', 19),
('Kupang', 19),
('Bengkayang', 20),
('Kapuas Hulu', 20),
('Kayong Utara', 20),
('Ketapang', 20),
('Kubu Raya', 20),
('Landak', 20),
('Melawi', 20),
('Mempawah', 20),
('Sambas', 20),
('Sanggau', 20),
('Sekadau', 20),
('Sintang', 20),
('Pontianak', 20),
('Singkawang', 20),
('Balangan', 21),
('Banjar', 21),
('Barito Kuala', 21),
('Hulu Sungai Selatan', 21),
('Hulu Sungai Tengah', 21),
('Hulu Sungai Utara', 21),
('Kotabaru', 21),
('Tabalong', 21),
('Tanah Bumbu', 21),
('Tanah Laut', 21),
('Tapin', 21),
('Banjarbaru', 21),
('Banjarmasin', 21),
('Barito Selatan', 22),
('Barito Timur', 22),
('Barito Utara', 22),
('Gunung Mas', 22),
('Kapuas', 22),
('Katingan', 22),
('Kotawaringin Barat', 22),
('Kotawaringin Timur', 22),
('Lamandau', 22),
('Murung Raya', 22),
('Pulang Pisau', 22),
('Sukamara', 22),
('Seruyan', 22),
('Palangka Raya', 22),
('Berau', 23),
('Kutai Barat', 23),
('Kutai Kartanegara', 23),
('Kutai Timur', 23),
('Mahakam Ulu', 23),
('Paser', 23),
('Penajam Paser Utara', 23),
('Balikpapan', 23),
('Bontang', 23),
('Samarinda', 23),
('Bulungan', 24),
('Malinau', 24),
('Nunukan', 24),
('Tana Tidung', 24),
('Tarakan', 24),
('Boalemo', 25),
('Bone Bolango', 25),
('Gorontalo', 25),
('Gorontalo Utara', 25),
('Pohuwato', 25),
('Gorontalo', 25),
('Bantaeng', 26),
('Barru', 26),
('Bone', 26),
('Bulukumba', 26),
('Enrekang', 26),
('Gowa', 26),
('Jeneponto', 26),
('Kepulauan Selayar', 26),
('Luwu', 26),
('Luwu Timur', 26),
('Luwu Utara', 26),
('Maros', 26),
('Pangkajene dan Kepulauan', 26),
('Pinrang', 26),
('Sidenreng Rappang', 26),
('Sinjai', 26),
('Soppeng', 26),
('Takalar', 26),
('Tana Toraja', 26),
('Toraja Utara', 26),
('Wajo', 26),
('Makassar', 26),
('Palopo', 26),
('Parepare', 26),
('Bombana', 27),
('Buton', 27),
('Buton Selatan', 27),
('Buton Tengah', 27),
('Buton Utara', 27),
('Kolaka', 27),
('Kolaka Timur', 27),
('Kolaka Utara', 27),
('Konawe', 27),
('Konawe Kepulauan', 27),
('Konawe Selatan', 27),
('Konawe Utara', 27),
('Muna', 27),
('Muna Barat', 27),
('Wakatobi', 27),
('Bau-Bau', 27),
('Kendari', 27),
('Banggai', 28),
('Banggai Kepulauan', 28),
('Banggai Laut', 28),
('Buol', 28),
('Donggala', 28),
('Morowali', 28),
('Morowali Utara', 28),
('Parigi Moutong', 28),
('Poso', 28),
('Sigi', 28),
('Tojo Una-Una', 28),
('Toli-Toli', 28),
('Palu', 28),
('Bolaang Mongondow', 29),
('Bolaang Mongondow Selatan', 29),
('Bolaang Mongondow Timur', 29),
('Bolaang Mongondow Utara', 29),
('Kepulauan Sangihe', 29),
('Kepulauan Siau Tagulandang Biaro', 29),
('Kepulauan Talaud', 29),
('Minahasa', 29),
('Minahasa Selatan', 29),
('Minahasa Tenggara', 29),
('Minahasa Utara', 29),
('Bitung', 29),
('Kotamobagu', 29),
('Manado', 29),
('Tomohon', 29),
('Majene', 30),
('Mamasa', 30),
('Mamuju', 30),
('Mamuju Tengah', 30),
('Mamuju Utara', 30),
('Polewali Mandar', 30),
('Mamuju', 30),
('Buru', 31),
('Buru Selatan', 31),
('Kepulauan Aru', 31),
('Maluku Barat Daya', 31),
('Maluku Tengah', 31),
('Maluku Tenggara', 31),
('Maluku Tenggara Barat', 31),
('Seram Bagian Barat', 31),
('Seram Bagian Timur', 31),
('Ambon', 31),
('Tual', 31),
('Halmahera Barat', 32),
('Halmahera Tengah', 32),
('Halmahera Utara', 32),
('Halmahera Selatan', 32),
('Kepulauan Sula', 32),
('Halmahera Timur', 32),
('Pulau Morotai', 32),
('Pulau Taliabu', 32),
('Ternate', 32),
('Tidore Kepulauan', 32),
('Asmat', 33),
('Biak Numfor', 33),
('Boven Digoel', 33),
('Deiyai', 33),
('Dogiyai', 33),
('Intan Jaya', 33),
('Jayapura', 33),
('Jayawijaya', 33),
('Keerom', 33),
('Kepulauan Yapen', 33),
('Lanny Jaya', 33),
('Mamberamo Raya', 33),
('Mamberamo Tengah', 33),
('Mappi', 33),
('Merauke', 33),
('Mimika', 33),
('Nabire', 33),
('Nduga', 33),
('Paniai', 33),
('Pegunungan Bintang', 33),
('Puncak', 33),
('Puncak Jaya', 33),
('Sarmi', 33),
('Supiori', 33),
('Tolikara', 33),
('Waropen', 33),
('Yahukimo', 33),
('Yalimo', 33),
('Jayapura', 33),
('Fakfak', 34),
('Kaimana', 34),
('Manokwari', 34),
('Manokwari Selatan', 34),
('Maybrat', 34),
('Pegunungan Arfak', 34),
('Raja Ampat', 34),
('Sorong', 34),
('Sorong Selatan', 34),
('Tambrauw', 34),
('Teluk Bintuni', 34),
('Teluk Wondama', 34);